services:
  postgres:
    container_name: postgis-bd2
    image: postgis/postgis:latest
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database
    ports:
      - '5432:5432'  
    volumes:
      - 'polls_pg_data:/projects/postgresql'

  pgadmin:
    container_name: pgadmin-bd2
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
       - "5050:80"


volumes: 
  polls_pg_data:
